Repository renatismos/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#2 Integrar requisitos v1.0
  docs/requisitos.md
Labels: Análise

#6 V1.0 arquitetura
  docs/arquitetura.md
Labels: Arquitetura

#7 Integrar implementação v1.0
  src/jogovelha.py
Labels: Programação

#8 Integrar testes v1.0
  src/testes_inic.py
  src/testes_jogar.py
Labels: Testes

#9 Gerar release v1.0
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: Operações

#15 V1.1 programacao
  src/jogovelha1.1.py
Labels: Programação

#14 Integrar testes v1.1
  src/testes_inic.py
  src/testes_jogar.py
Labels: Testes

#16 Update jogovelhav1.1.py
  src/jogovelhav1_1.py
Labels: Análise

#18 Integrar arquitetura v1.1
  docs/arquitetura.md
Labels: Arquitetura

#19 Integrar implementação v1.2
  src/jogovelha2.py
Labels: Programação

#20 Gerar release v1.1
  docs/arquitetura.md
  src/jogovelha1.1.py
  src/jogovelha2.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: Operações
